### PR TITLE
added a new question

### PR DESCRIPTION
**Pull request by Joshua-Page**

### CODE REVIEW

**Comment by nas5w** [comment]
Thanks @Joshua-Page! I made a proposed edit to make the question a bit more challenging. What do you think of the new wording?

**Comment by Joshua-Page** [comment]
Looks good! Thanks for the edit.

**Comment by nas5w** [comment]
Awesome! I'm trying to figure out the best way to list contributors on the app, hopefully I can list you up there soon!

**Comment by nas5w** [comment]
Question is live! 

https://quiz.typeofnan.dev/array-loop-largest-number/

Thanks again

**Comment by Joshua-Page** [comment]
Awesome. I will keep racking my brain for some more questions!

**Pull request merged**
