### PR TITLE
Add a numeric literal mind-bender.

### PR DESCRIPTION
**Pull request by michaelsanford**
More underused JavaScript fun.

I had originally used a markdown list for the explanation, but the bullet alignment was poor in the answer pane and I preferred not to play with global styles for a simple PR.

### CODE REVIEW

**Comment by michaelsanford** [comment]
Squashed and force pushed to add some missing topic tags.

**Comment by nas5w** [comment]
I'm conflicted on this one. I kind of want to keep the quizzes more... practical. What do you think?

**Comment by michaelsanford** [comment]
@nas5w It's your project and is subject to your vision 👍 

I did consider this, though.

I intentionally included plausible error messages to allow two thinking branches: 
1) _I should obviously choose an error, these aren't numbers!_ in which case they've never seen anything but decimal notation (and IMHO should learn of their existence), or
2) _Oh yes, let's work this out!_ - an interesting challenge.

In the first case, the elaborated explanation is a didactic tool to introduce the neophyte to non-base-ten literal notation in all its forms.

I personally think this sort of quiz is _the best_ place to learn things like:

- _No way, `017 != 17` I had no idea! I'll remember that if I ever need it!_
- _Cool, you can use binary/hex directly in JavaScript without converting it, that might come in handy._

as I wouldn't expect these concepts to be pervasive in bootcamps or tutorials. I figured that was part of the goal of this project, but it may not be, or this may not be the way _you want to go about it_.

If you'd rather more straightforward questions, I won't be dissuaded from contributing further along those lines.

**Comment by michaelsanford** [comment]
Happy new year! 🎉

**Pull request closed without merging**
